spring.application.name=platzi-play-test
server.port=8081
server.servlet.context-path=/dev/api

# Langchain4j Settings

langchain4j.open-ai.chat-model.api-key=demo
langchain4j.open-ai.chat-model.log-request=true
langchain4j.open-ai.chat-model.log-responses=true
logging.level.dev.langchain4j=DEBUG
logging.level.dev.ai4j.openai4j=DEBUG