services:
  mongodb:
    image: mongo:latest
    container_name: mdb_local
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_admin
      MONGO_INITDB_ROOT_PASSWORD: password_seguro
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
